# Generated by Django 3.1.7 on 2021-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equities',
            name='company_label',
            field=models.ImageField(blank=True, null=True, upload_to='companiesLogo/', verbose_name='company_logo'),
        ),
    ]
