# Generated by Django 3.1.7 on 2021-04-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0002_equities_company_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equities',
            name='company_label',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='company_logo'),
        ),
    ]
