# Generated by Django 3.1.7 on 2021-04-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0003_auto_20210423_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, choices=[('ST', 'Ученик'), ('AD', 'Преподователь'), ('GR', 'Выпускник')], default='ST', max_length=2, null=True)),
            ],
        ),
    ]
