# Generated by Django 3.1.7 on 2021-04-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0005_delete_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Имя группы')),
                ('group_age', models.CharField(blank=True, choices=[('Little', '7-10 лет'), ('Middle', '10-14 лет'), ('Old', '14-17 лет'), ('Teacher', 'Преподаватели')], default='Middle', max_length=7, null=True, verbose_name='Возраст')),
            ],
        ),
    ]
