# Generated by Django 3.1.7 on 2021-04-29 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainCoins', '0006_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.IntegerField(default=0)),
                ('status_name', models.CharField(blank=True, choices=[('ST', 'Ученик'), ('DU', 'Удаленный студент'), ('GR', 'Выпускник')], default='ST', max_length=2, null=True)),
                ('equities', models.ManyToManyField(blank=True, null=True, to='mainCoins.Equities')),
                ('group', models.ManyToManyField(blank=True, null=True, to='mainCoins.Groups')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
