# Generated by Django 3.1.7 on 2021-04-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0007_studentsinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsInfo',
        ),
    ]
