# Generated by Django 3.1.7 on 2021-04-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0010_studentsinfo_equities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainCoins.groups'),
        ),
    ]
