# Generated by Django 3.1.7 on 2021-04-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0012_teachersinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersinfo',
            name='group',
        ),
        migrations.AddField(
            model_name='teachersinfo',
            name='group',
            field=models.ManyToManyField(to='mainCoins.Groups'),
        ),
    ]
