# Generated by Django 3.1.7 on 2021-05-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0013_auto_20210429_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsinfo',
            name='group',
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='group',
            field=models.ManyToManyField(null=True, to='mainCoins.Groups'),
        ),
    ]
