# Generated by Django 3.1.7 on 2021-05-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0015_auto_20210506_0525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinCoins',
        ),
    ]
