# Generated by Django 3.1.7 on 2021-05-06 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0017_auto_20210506_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsinfo',
            name='group',
        ),
        migrations.AddField(
            model_name='studentsinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainCoins.groups'),
        ),
    ]
