# Generated by Django 3.1.7 on 2021-05-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0018_auto_20210506_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainCoins.groups'),
        ),
    ]
