# Generated by Django 3.1.7 on 2021-05-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0023_auto_20210510_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер телефона'),
        ),
    ]
