# Generated by Django 3.1.7 on 2021-05-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0024_auto_20210510_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
