# Generated by Django 3.1.7 on 2021-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0026_auto_20210510_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
