# Generated by Django 3.1.7 on 2021-05-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0027_studentsinfo_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Имя группы'),
        ),
    ]
