# Generated by Django 3.1.7 on 2021-05-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0028_auto_20210511_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Имя'),
        ),
    ]
