# Generated by Django 3.1.7 on 2021-05-11 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainCoins', '0029_studentsinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='user_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
