# Generated by Django 3.1.7 on 2021-05-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0030_auto_20210511_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
