# Generated by Django 3.1.7 on 2021-05-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0031_auto_20210512_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='second_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Фамилия'),
        ),
    ]
