# Generated by Django 3.1.7 on 2021-05-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0032_auto_20210512_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True, unique=True, verbose_name='Адресс Электронной почты'),
        ),
        migrations.AddField(
            model_name='teachersinfo',
            name='name',
            field=models.CharField(max_length=32, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teachersinfo',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='teachersinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='teachersinfo',
            name='second_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teachersinfo',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
