# Generated by Django 3.1.7 on 2021-05-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0033_auto_20210513_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersinfo',
            name='is_super_user',
            field=models.BooleanField(blank=True, null=True, verbose_name='СуперАдмин'),
        ),
        migrations.AlterField(
            model_name='teachersinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='teachersinfo',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Пароль'),
        ),
    ]
