# Generated by Django 3.1.7 on 2021-05-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0034_auto_20210513_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersinfo',
            name='is_super_user',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Суперадмин'),
        ),
    ]
