# Generated by Django 3.1.7 on 2021-05-14 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainCoins', '0036_auto_20210513_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachersinfo',
            name='who_add_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='who_add_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
