# Generated by Django 3.1.7 on 2021-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0037_teachersinfo_who_add_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersinfo',
            name='email',
            field=models.EmailField(max_length=32, unique=True, verbose_name='Адрес электронной почты'),
        ),
    ]
