# Generated by Django 3.1.7 on 2021-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0038_auto_20210514_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
