# Generated by Django 3.1.7 on 2021-05-15 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0039_groups_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_age',
            field=models.CharField(blank=True, choices=[('Little', '7-10 лет'), ('Middle', '10-14 лет'), ('Old', '14-17 лет')], default='Middle', max_length=7, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='studentsinfo',
            name='coins',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
