# Generated by Django 3.1.7 on 2021-05-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0040_auto_20210515_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='equities',
            name='company_url',
            field=models.URLField(blank=True, default='https://www.finam.ru/quote', null=True),
        ),
    ]
