# Generated by Django 3.1.7 on 2021-05-17 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0041_equities_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='equities',
            name='date_of_last_update',
            field=models.DateField(default=datetime.datetime(2021, 5, 17, 7, 7, 23, 337937)),
        ),
        migrations.AlterField(
            model_name='equities',
            name='company_url',
            field=models.URLField(blank=True, default='https://www.finam.ru', null=True),
        ),
    ]
