# Generated by Django 3.1.7 on 2021-05-17 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0042_auto_20210517_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equities',
            name='date_of_last_update',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
