# Generated by Django 3.1.7 on 2021-05-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0044_equities_company_label_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='equities',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
