# Generated by Django 3.1.7 on 2021-05-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0045_equities_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsinfo',
            name='notifications',
            field=models.CharField(max_length=255, null=True, verbose_name='Уведомеления'),
        ),
    ]
