# Generated by Django 3.1.7 on 2021-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainCoins', '0047_auto_20210518_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='notifications',
            field=models.TextField(max_length=4000, null=True, verbose_name='Уведомеления'),
        ),
    ]
